#!/bin/bash
#SBATCH --job-name=timeseries_unified_3d
#SBATCH --partition=gpu_short
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-gpu=2G
#SBATCH --time          01:00:00
#SBATCH --output        slogs/timeseries_unified_3d.%j.out
#SBATCH --error         slogs/timeseries_unified_3d.%j.err
#SBATCH --exclude       compg009,compg010,compg011,compg013
#SBATCH --constraint    "a100"

# 3D Unified Autoregressive Timeseries Generation
#
# Generates N frames autoregressively using a single unified checkpoint:
#
#   V_0 ~ p(V | heatmap_0,  zeros    )    [no previous frame]
#   V_1 ~ p(V | heatmap_1,  V_0→[0,1])
#   V_2 ~ p(V | heatmap_2,  V_1→[0,1])
#   ...
#
# Prerequisites:
#   1. Trained unified checkpoint:  checkpoints/unified_3d/best.pt
#   2. Centre files in CENTRES_DIR: synthetic_3d_NNNN_centres.npy
#      (generated by scripts/generate_synthetic3d.py or similar)
#
# Run with:
#   sbatch SLURM/slurm_timeseries_unified_3d.sl

module purge
source /well/kir/config/modules.sh
module load Python/3.10.8-GCCcore-12.2.0
module load CUDA/12.0
source ~/devel/venv/Python-3.10.8-GCCcore-12.2.0/cell_simul_env/bin/activate

WORK_DIR="/users/kir-fritzsche/aif490/devel/tissue_analysis/CellSimul_diff"
cd $WORK_DIR

# ── Configuration ──────────────────────────────────────────────────────────────

CHECKPOINT="/users/kir-fritzsche/aif490/devel/tissue_analysis/CellSimul_diff/checkpoints/unified_3d_node1_C_no_cfg_SNR/checkpoint_step_205000.pt"
CONFIG="configs/unified_3d.yaml"

# Directory containing synthetic_3d_NNNN_centres.npy files
CENTRES_DIR="synthetic_cells_3d"

# First timepoint index and total number of frames to generate
START_T=0
NUM_FRAMES=4

VOLUME_SIZE=128

# Output directory — a subdirectory per run is recommended
OUT_DIR="timeseries_output/unified_3d_C_no_cfg"

# Classifier-free guidance  (true / false)
USE_CFG=false
GUIDANCE_SCALE=1.0          # frames 1+
GUIDANCE_SCALE_T0=0.0       # frame 0 only (heatmap-only conditioning → can be higher)

# Load EMA weights from checkpoint (recommended for best quality)
USE_EMA=false

# Heatmap sigma (voxels) — should match the value used during training
HEATMAP_SIGMA=5.0

# Centre generation method: from_files | realistic
METHOD="realistic"

# Inter-frame Gaussian displacement std-dev (voxels) — only used when METHOD=realistic
DISPLACEMENT_SIGMA=2

# Random seed for centre generation (leave empty for a random seed each run)
SEED=""

# Save heatmap TIFs alongside each generated volume (true / false)
SAVE_HEATMAPS=true

# Match each frame's histogram to the previous frame to suppress intensity drift
# (true / false — default false; only meaningful at inference with many frames)
MATCH_HISTOGRAMS=true

# Fraction of denoising steps (from t=0, low-noise end) during which the
# prev-frame channel is active. 0.3 = heatmap drives placement for 70% of steps,
# prev_vol contributes texture for the final 30%. 1.0 = always active (no change).
PREV_VOL_ACTIVE_FRAC=0.9

# Number of independent timeseries to generate.
# With METHOD=realistic each sample gets its own centre sequence.
# With METHOD=from_files all samples share the same centres; diversity comes from diffusion noise.
NUM_SAMPLES=1

# How many samples to process simultaneously as a GPU batch.
# Higher = faster but uses proportionally more GPU memory.
# Rule of thumb: 4 samples × 128^3 at float32 ≈ 2 GB extra VRAM.
SAMPLE_BATCH_SIZE=1

# Voxel padding around the visible volume used for simulation (METHOD=realistic only).
# Centres are simulated in (VOLUME_SIZE + 2*PADDING)³; only those inside the central
# VOLUME_SIZE³ region contribute to the heatmap.  Cells that drift outside appear as
# NaN rows in saved centre files, preserving row-index = instance-ID across frames.
# Set to 0 to disable (cells clamp at border, old behaviour).
SIMULATION_PADDING=16

# ──────────────────────────────────────────────────────────────────────────────

echo "========================================================"
echo "3D Unified Timeseries Generation"
echo "========================================================"
echo "Job ID:    $SLURM_JOB_ID"
echo "Node:      $SLURM_NODELIST"
echo "GPU:       $CUDA_VISIBLE_DEVICES"
echo "Start:     $(date)"
echo "Checkpoint: $CHECKPOINT"
echo "Config:     $CONFIG"
echo "guidance_scale: $GUIDANCE_SCALE (t>0), $GUIDANCE_SCALE_T0 (t=0)"
echo "match_histograms: $MATCH_HISTOGRAMS"
echo "save_heatmaps: $SAVE_HEATMAPS"
echo "use_cfg: $USE_CFG"
echo "use_ema: $USE_EMA"
echo "seed: $SEED"
echo "heatmap_sigma: $HEATMAP_SIGMA"
echo "method: $METHOD"
echo "PREV_VOL_ACTIVE_FRAC: $PREV_VOL_ACTIVE_FRAC"
echo "displacement_sigma: $DISPLACEMENT_SIGMA"
echo "Method:     $METHOD  (centres_dir=$CENTRES_DIR  sigma=$DISPLACEMENT_SIGMA)"
echo "Frames:     $NUM_FRAMES  (t=$START_T … t=$(( START_T + NUM_FRAMES - 1 )))"
echo "Samples:    $NUM_SAMPLES  (batch_size=$SAMPLE_BATCH_SIZE)"
echo "Sim padding: $SIMULATION_PADDING vox"
echo "Output:     $OUT_DIR"
echo "========================================================"

python -c "import torch; print('GPU:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'none')"

# Build command
CMD="python scripts/generate_timeseries_unified_3d.py \
    --checkpoint $CHECKPOINT \
    --config     $CONFIG \
    --method     $METHOD \
    --centres_dir $CENTRES_DIR \
    --displacement_sigma $DISPLACEMENT_SIGMA \
    --start_t    $START_T \
    --num_frames $NUM_FRAMES \
    --volume_size $VOLUME_SIZE \
    --out_dir    $OUT_DIR \
    --heatmap_sigma $HEATMAP_SIGMA \
    --guidance_scale $GUIDANCE_SCALE \
    --guidance_scale_t0 $GUIDANCE_SCALE_T0 \
    --prev_vol_active_frac $PREV_VOL_ACTIVE_FRAC \
    --num_samples $NUM_SAMPLES \
    --sample_batch_size $SAMPLE_BATCH_SIZE \
    --simulation_padding $SIMULATION_PADDING"

if [ "$USE_CFG" = "true" ]; then
    CMD="$CMD --cfg"
fi

if [ "$USE_EMA" = "true" ]; then
    CMD="$CMD --use_ema"
fi

if [ -n "$SEED" ]; then
    CMD="$CMD --seed $SEED"
fi

if [ "$SAVE_HEATMAPS" = "true" ]; then
    CMD="$CMD --save_heatmaps"
fi

if [ "$MATCH_HISTOGRAMS" = "true" ]; then
    CMD="$CMD --match_histograms"
fi

echo ""
echo "Command: $CMD"
echo ""

eval $CMD
EXIT_CODE=$?

echo ""
echo "========================================================"
if [ $EXIT_CODE -eq 0 ]; then
    echo "Generation complete!  ($NUM_SAMPLES sample(s))"
    echo "Volumes written to: $OUT_DIR"
else
    echo "Generation FAILED with exit code $EXIT_CODE"
fi
echo "End: $(date)"
echo "========================================================"

exit $EXIT_CODE
